### ISSUE TITLE
Parámetro user en docker-compose

### ISSUE THREAD

**Issue by garanda21** [dgongut/docker-controller-bot#52]
Si tienes un docker configurado con el parámetro [user](https://docs.docker.com/reference/compose-file/services/#user)

```yml
services:
  mydocker:
    image: myimage:latest
    network_mode: bridge
    user: root <---- Esta línea 
    ports:
    - 8081:8080/tcp
```

Y actualizas el contenedor desde el bot, dicho parámetro se pierde y debes añadirlo manualmente.
